### ISSUE TITLE
Is there a way of getting Banshee to run on PHP5.6 instead of PHP7.0 

### ISSUE THREAD

**Issue by marxenegls** [hsleisink/banshee#10]
Documentation states minimum php7 , though I've been trying in vain to get the whole thing up and running with php5.6 . I have set up fastcgi php5-fpm xsl xml parser gd mysql etc..  installed spawn-fcgi too . I get Hiawatha works page including the https , but i'm failing to get banshee or monitor  which reside in /var/www/example.net/hiawatha/banshee-master/public respectively., now trying them within hiawatha's directory , they had their own initially /var/www/example.com/banshee .didn't work. I created the banshee_db, edited the php.ini params and cron hourly as stated in README.md with crontab -e , still no banshee. Is there an Alias directive for Virtaulhost ?I've given each site its own virtualhost name .
 Is the CGIextension handler needed along with php5-fastcgi ? is the Vhost interface = x.x.x.x ip required? 
What am i missing ?  apache2 stop  , now i see localhost displaying apache's Index dir, that cant be right.
  I have access to phpmyadmin from localhost which allowed me to pull in the database mysql.sql for both monitor and banshee .. why am i being redirected to localhost when i give the virthost url www.banshee.example.net ?
  why both monitor and banshee are failing monitor should be ok with php5 , i'm getting service unavailable 503 www.monitor.example.net and occasionally it points me back to localhost and apache's index

**Comment by hsleisink** [comment]
Hi,

If you’re using PHP 5, use Banshee v5.x. Banshee v6.x requires PHP 7. All you need to know to install Banshee is written in the INSTALL file. And I need more than “it didn’t work” to understand what goes wrong.

Hugo
