### ISSUE TITLE
Improved menu editor in CMS (jQuery)

### ISSUE THREAD

**Issue by hsleisink** [hsleisink/banshee#4]
The Banshee CMS has a menu editor, written in Javascript and using jQuery. An example of how it works can be found at https://demo.banshee-php.org/cms/menu (username 'admin', password 'banshee'). The main problem is that when a submenu item is moved to another location, it becomes a main menu item (no indent). What I want is that when I drop a menu item on top of another menu item, it becomes its child. I'm not a Javascript / jQuery expert, so I could use some help with that. Any other improvements are also welcome.

The file that handles the menu editing is public/js/banshee/jquery.menueditor.js. A complete rewrite of that library is of course allowed.

The files that handle the submit are controllers/cms/menu.php and models/cms/menu.php, but they probably don't need to be changed.

**Comment by StyxOfDynamite** [comment]
Looks like a fun one, what sort of timeframes are you looking at for expediting a solution ?

Also you say "When you drop" but I can't see any drag / drop interface, just the "add" buttons, any chance you could attach a gif showing the current behaviour ?

**Comment by thepassenger-hub** [comment]
Took me a while to understand your problem. Maybe you should hint in the menu page that the items are draggable. Anyway I see that if you drag a child it becomes a main item, let's call it parent. What should be the correct behaviour though?
 ```What I want is that when I drop a menu item on top of another menu item, it becomes its child.```

What about a depth of 2 ? Should a child of a child become the child of the child of the other item or just a child of depth 1? What I'm trying to say is, I think you just want to keep the hierarchy as it is right? 

Agree with @StyxOfDynamite this looks like fun.

**Comment by StyxOfDynamite** [comment]
Even knowing they are draggable, I can't seem to drag them, do I need to be clicking a certain part of the menu item?

Version 61.0.3163.100 (Official Build) (64-bit) (MacOS Sierra)

**Comment by hsleisink** [comment]
@StyxOfDynamite No rush at all. I recently released v6.1, so it will take probably a few months before I will release the next version.

@thepassenger-hub Good point. The addition of some sort of you-can-drag me icon is also welcome. It would be very awesome if the editor allows any kind of dragging. An intuitive editor that allows any kind of adding, deleting and moving of menu items.

**Comment by thepassenger-hub** [comment]
@StyxOfDynamite Try between the 2 input fields. All the line except the 2 input fields and button are draggable for me.

**Comment by StyxOfDynamite** [comment]
Nice pointer @thepassenger-hub - OK,

looks like we both know what the requirements are then.

@hsleisink How are the menu's persisted on the backend? - Maybe one of us can look at storing the config and the other building it ?

**Comment by hsleisink** [comment]
The files controllers/cms/menu.php and models/cms/menu.php take care of writing the menu to the database. If you submit the menu the same way the current jQuery library does, you don't have to change those files.

**Comment by hsleisink** [comment]
Any progress on the menu editor?

**Comment by StyxOfDynamite** [comment]
I was waiting to be assigned the issue before cracking on incase, you wanted to assign it to  @thepassenger-hub -  If you assign in to me, I can probably get a PR in before Friday :)

**Comment by hsleisink** [comment]
Oh, ok. Didn't know you were waiting for an assignment. I have no preference of who builds it, but since you responded first, I'll assign you, Styx.

**Comment by StyxOfDynamite** [comment]
Over there on the right -> you should be able to click assign.

**Comment by StyxOfDynamite** [comment]
I guess because I'm not a collaborator, no worries, I'll ping in an empty PR, reference this issue so anyone else can see its being worked on that way.
