### ISSUE TITLE
Design a logo for the Banshee PHP framework

### ISSUE THREAD

**Issue by hsleisink** [hsleisink/banshee#5]
Design a nice logo for the Banshee PHP framework. It would also be nice to have a favicon version of that logo.

Background story for the name of this framework: I really like to play Dungeons & Dragons. My first framework was called Skeleton (a framework being the skeleton of a website). I did a complete rewrite of that framework and looked for a new name. A Banshee is a stronger undead creature than the Skeleton, so I took that one. Although a picture of a Banshee I found on the internet is shown at the Banshee website, I don't use it as its logo.

**Comment by DigitalDesignerOnline** [comment]
I would be happy to assist, I can get this to you today.

**Comment by DigitalDesignerOnline** [comment]
what about something like this?
![banshee-logo](https://user-images.githubusercontent.com/25376856/31229995-882e6a78-a9b0-11e7-965a-3591b1c130c3.png)

**Comment by DigitalDesignerOnline** [comment]
I can get the pull request setup now if you like it.

**Comment by hsleisink** [comment]
Holy crap! That's quick and awesome!! Can you tell me which font you used? I'd like to use that font throughout the website as well (headers etc).

**Comment by DigitalDesignerOnline** [comment]
Use Google Fonts Papyrus, will add the file to the site and drop in the pull request in a hot second. Glad that you like the design

**Comment by hsleisink** [comment]
Just to be sure: this image is free of use? Did you draw it yourself or what is the source?

**Comment by DigitalDesignerOnline** [comment]
I bought a stock image, I can send you the main file as well Or if oyu want to wait til tongiht after I am done work I can create one from scratch. It is a royalty free image purchased from 123rf.com that I altered so you should not have any legal ramifications at all.

**Comment by DigitalDesignerOnline** [comment]
i never google images ;)

**Comment by DigitalDesignerOnline** [comment]
I was working on a halloween project and grabbed a tonne of images earlier today when I saw your post was like I have one for that lol. Already replaced my ghostly image for the flyer I am making :)

**Comment by hsleisink** [comment]
What do you mean with 'from scratch'?

**Comment by hsleisink** [comment]
No need for a font pull request. The name of the font is enough. Thanks!

**Comment by hsleisink** [comment]
On second thought, can you send me your Papyrus ttf file? I can't find a free font that looks the same. Can you also send me the logo without the text?

**Comment by karillith** [comment]
Is this already completed? I'd actually like to do some original artwork and get you a favicon as well. Let me know, thanks :)

**Comment by hsleisink** [comment]
Well, I already got a logo with text (as you can see in a previous comment). I asked the designer for a logo without the text and the font file. No response yet. Although it's a pre-made logo, I like it a lot.

You are welcome to show me your artwork. I like the idea of having a unique logo, because I have no idea where and how the logo I received is also being used.

**Comment by DigitalDesignerOnline** [comment]
sorry mate, I was away for the long weekend as it was Thanksgiving here in Canada, didn't mean to disappear on ya like that. :) regarding font, you can always check out dafont.com let me know the font you like and I can add it in. Here is the graphic I used for the design.
[hsleisink.zip](https://github.com/hsleisink/banshee/files/1373348/hsleisink.zip)

**Comment by hsleisink** [comment]
Thanks!! No problem. Sounds like a good excuse to be away.

**Comment by DigitalDesignerOnline** [comment]
oh and here is the favicon gfx
![favicon](https://user-images.githubusercontent.com/25376856/31412337-aa0d8a9e-ade2-11e7-96f8-4b1b449ed2d6.png)

**Comment by DigitalDesignerOnline** [comment]
original artwork is always best but I was strapped for time for the family visits and all that jazz, looking forward to seeing what @karillith creates.

**Comment by DigitalDesignerOnline** [comment]
i went with the specific stock as it had 4 images and could be used for future versions as well  this way as they are all in the same theme ;)

**Comment by karillith** [comment]
https://drive.google.com/drive/folders/0BzWiSzS6AtR9YUpCS1F0NlZmckk?usp=sharing 
The font I used was Nosifer: https://fonts.google.com/specimen/Nosifer

**Comment by hsleisink** [comment]
Interesting. Very interesting. My first thought was: nice logo, but it looks more like a nice girl than a banshee. But I gave it some more thought. I'm no expert in marketing etc, but it made me wonder what other people would think of a hideous creature as a logo. Your logo may not look like a banshee, but it might be more pleasant to look at. What to do...?

What's the idea of the lock in the logo? Or is it a Google Drive thing?

**Comment by dhdutoit** [comment]
With the issue still being open I would throw in an alternative approach for a logo. These are two versions made in Gimp using commercially free-to-use fonts, free brushes and free colour palette (all links to creators available, as well the gimp file). These do not use the actual image of a banshee and rather leans towards the popular approach of a simple logo, playing more on recognisable colours. Hope you like it, but even if not your feedback would be welcome. :)

![banshee-logo-two](https://user-images.githubusercontent.com/13850384/31441961-22a8b3a4-ae95-11e7-9e3f-59e0b7d6dde3.png)
![banshee-logo-one](https://user-images.githubusercontent.com/13850384/31441964-22d86cfc-ae95-11e7-9d06-8b099d3d7708.png)

**Comment by hsleisink** [comment]
Thanks for your input, dhdutoit. I understand what you're saying. I'm no design expert, so no offense, but to me these logo's don't look like a logo for a CMS or framework. The second more girl like logo made me indeed think about a real banshee-like logo like the first one. A real banshee-like logo might indeed not be the best choice, although I liked that image. But a complete non-banshee like logo... I don't know. Sorry, perhaps it's too much of a change for me right now.

**Comment by karillith** [comment]
@hsleisink I drew it myself. The lock is a reference to this framework having an emphasis on security. Figured it could be a nice tie-in between the name and the use.

**Comment by dhdutoit** [comment]
@hsleisink , thank you for the feedback. Appreciate it. :)

**Comment by hsleisink** [comment]
@karillith I've placed your logo at the Banshee website (https://www.banshee-php.org/) as a test. I've not decided yet, just for me to get an idea of how it looks. I've made small changes: removed the lock, added a bit transparency and styled the text. Do you agree with the changes I made? After all, it's your artwork.

**Comment by karillith** [comment]
@hsleisink  I like the additional styling on the font! I can send you a version of the image with a transparent bg and sans lock if you'd like in a couple hours.

**Comment by juliadebelli** [comment]
hey, I gave it a try. It's just a sketch, if you like it I can make a real version :)

<img width="641" alt="screen shot 2017-10-13 at 12 06 44" src="https://user-images.githubusercontent.com/19510532/31552860-00251860-b00f-11e7-8f95-1c4ceb289645.png">

**Comment by juliadebelli** [comment]
hey there, I gave it a try. It's just a concept sketch, if you like it I can make a polished version and also modify it according to feedback

<img width="665" alt="screen shot 2017-10-13 at 12 08 49" src="https://user-images.githubusercontent.com/19510532/31552951-47153f02-b00f-11e7-8ed3-b7f2d25d9bc3.png">

**Comment by hsleisink** [comment]
@karillith Just a version without the lock and a transparent background would be great. I'll take care of the font. I think I'll go for your logo after all. 

@juliadebelli Thanks for your logo, but that's not what I'm looking for.

**Comment by hsleisink** [comment]
@karillith My decided to pick your logo as the new one for Banshee. Thanks a lot!

Also thanks to the rest who made a proposal logo.
