### ISSUE TITLE
OAuth 2.0 integration?

### ISSUE THREAD

**Issue by akak0r** [hsleisink/banshee#9]
Hi,

would it be possible to include OAuth 2.0 login (e.g. login by using your Facebook or Google credentials) in a next version?

Thanks!

**Comment by hsleisink** [comment]
Sorry, but that's something I won't do. Letting others do the user management is very bad from a security point of view. And Facebook and Google from a privacy point of view, well... OAuth is bad for security and bad for privacy.

**Comment by akak0r** [comment]
You have a very valid point. A lot of people don't care though and just want to login in the easiest way possible. They don't want to create an extra username/pw combo for yet another website. But I totally understand (and agree with) your point of view.
